# Generated by Django 4.1 on 2022-09-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0002_alter_measurement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="date",
            field=models.DateField(default=False),
        ),
    ]
