# Generated by Django 4.1 on 2022-09-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0005_alter_measurement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
